[package]
name = "cdktr-db"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = {workspace = true}
cdktr-core = { workspace = true }
duckdb = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }