[book]
authors = ["nicelgueta"]
language = "en"
multilingual = false
src = "src"
title = "CDKTR Documentation"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
default-theme = "navy"
preferred-dark-theme = "navy"